# Generated by Django 2.0.4 on 2019-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190715_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('-', '-'), ('M', '男'), ('F', '女')], default='-', max_length=1),
        ),
    ]
